<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://local.github/soap/test" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://local.github/soap/test">
<types>
<xsd:schema targetNamespace="http://local.github/soap/test">
<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"></xsd:import>
<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"></xsd:import>
</xsd:schema>
</types>
<message name="GetTestStrRequest">
<part name="name" type="xsd:string"></part>
</message>
<message name="GetTestStrResponse">
<part name="return" type="xsd:string"></part>
</message>
<portType name="testPortType">
<operation name="GetTestStr">
<input message="tns:GetTestStrRequest">
<output message="tns:GetTestStrResponse"></output>
</operation>
</portType>
<binding name="testBinding" type="tns:testPortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
<operation name="GetTestStr">
<soap:operation soapAction="http://local.github/webservice/nusoap/nusoapService.php/GetTestStr" style="rpc"></soap:operation>
<input>
<soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"></soap:body>
</input>
<output>
<soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"></soap:body>
</output>
</operation>
</binding>
<service name="test">
<port name="testPort" binding="tns:testBinding">
<soap:address location="http://local.github/webservice/nusoap/nusoapService.php"></soap:address>
</port>
</service>
</definitions>